/*
-- Query: SELECT * FROM basco.qcheck_items as ci
-- join objfiles as f on f.objid=ci.id and f.sysobjid=863
LIMIT 0, 1000

-- Date: 2020-07-16 08:22
*/
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (1,1,1,'Проживание в границах строительной площадки.Не обустроено по нормативам.','ОТ','Фото:002,003','28.05.2020','Невельского','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (2,1,1,'Провалы грунта вдоль оси 1/1 , 19.',NULL,NULL,'28.05.2020',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (3,1,1,'Приготовление пищи на открытом огне.','ТБ','Фото:004,005','28.05.2020',NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (4,1,1,'Нет маркеров уровней строения (фасад)…..',NULL,NULL,'28.05.2020',NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (5,1,1,'Не акцентированны основной \'Рабочий ход\'','ТБ','Фото:011,013,017,018.','28.05.2020',NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (6,1,1,'Электрические щит(основной): Нет ответственного, место затопляемо. Щит 12 этаж - нештатное подключение.','ТБ','Фото:010,030,031.','28.05.2020',NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (7,1,1,'Увеличение и расширение технологических отверстий.','Отклон.','Фото:024,025,028,029.','28.05.2020',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (8,1,1,'Строительный мусор на начало смены.','ТБ','Фото:032.','28.05.2020',NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (9,2,1,'Мойка машин не осуществляется.','ОТ',NULL,'29.05.2020','Невельского','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (10,2,1,'Освещение в ночное время недостаточное, Сквозной проход вдоль южной строны невозможен.','ТБ',NULL,'30.05.2020',NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (11,3,1,'Увеличение провалов и сход грунта по линии гаражей, (за один раз увеличение в ширину составило 2400мм)','ЧС','Фото:34,35,36.','01.06.2020','Невельского','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (12,3,1,'Отставание по графику кладки.','Сроки',NULL,'02.06.2020',NULL,'Градстройгруп',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (13,4,1,'Общая планерка по объекту. Усилить отчетность суб.',NULL,'Протокол','02.06.2020','Невельского','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (14,4,1,'Не симетричны, не соблюдены размеры и положение арматурных каркасов, сварочные стыки, не последовательсти операционного процесса.','Качество','Фото: 044-048','03.06.2020',NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (15,5,1,'Отсутствие визуальной структурной схемы группы компании, контактный лист наполненый информацией.','Администр.',NULL,'04.06.2020','ОФИС БАСКО','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (16,6,1,'Проверка Договора Инстрой СК. -Наглядное пособие по необдуманности взятых обязательств с двух стронон. Несоблюдаются взятые обещания. Встреча с главным инж. Бургачев А.Л. Это подтверждает.','Администр.','п.п 1.3.3 ,1,3.5, 1.3.6, 2.2, 3.1.3.,3.2.,3,2.,3.3.,','03.06.2020','ОФИС БАСКО','Новостороев.',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (17,6,1,'Выезд на объект. Проверка условий договора: 1.Неравнозначные штрафные санкции. 2.Слишком укрупнен график производства. 3. Снижение цены контракта (дем.телпотрассы частично).','Администр.','п.п 7.3.,7.4..','04.06.2020','Гамарника 18Б','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (18,6,1,'Нарушение пож.безопастности при резке арматуры.','ТБ',NULL,'04.06.2020','Невельского','ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (19,7,1,'Некорректно работает электронная почта: Задержки с получением.','Администр.',NULL,'04.06.2020','ОФИС БАСКО','Новостороев.',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (20,7,1,'Кузнецова проблемма с ППТК, Ценовая политика Краспан, специалист по окнам Андрей.',NULL,NULL,'05.06.2020','Архфонд',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (21,7,1,'Нет актуальных графиков производства.',NULL,NULL,NULL,NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (22,8,1,'Обратная засыпка выполняется скальным грунтом, что отклонением от проекта и развалит всю изоляцию.','Качество','Фото 075.076','08.06.2020','Невельского','БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (23,8,1,'Нарушение пожарных и санитарных норм.','24','Фото 075.076',NULL,NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (25,8,1,'Бурение скважин подпорной стены. 7штук за 5дней. Это просто нерентабельно.',NULL,NULL,NULL,NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (26,9,1,'Нет технологических карт. Гл.инженер Балдин не уважительное отношение к заказчику и технадзору.','Качество',NULL,NULL,'Невельского','ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (27,9,1,'Проблемма с А400С',NULL,NULL,NULL,NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (28,9,1,'Совещание на объекте Проектировщики,Подрядчичи','Сроки',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (29,9,1,'Нет актуального графика ППР','Сроки',NULL,NULL,NULL,'БАСКО',1,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (30,10,1,'Совещение по ПОС Кузнецова Дренажи вдоль верхней подпорки\\.База для Бкрана, возможность разделения стилобатной части.','Качество',NULL,'09.06.2020','Кузнецова.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (31,11,1,'Качество работ по армированию желает лучшего. Геометрия и положение в плане имеют большие отклонения. Каркасы в опалубке во время заливки смещаются.','Качество','Фото 3829,3841','16.06.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (32,12,1,'Защитные слои несоблюдены','Качество',NULL,'18.06.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (33,12,1,'По Б2 отметки с 50.+ проемы не имеют правильной геометрии.','Качество','2156.1059.1508.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (34,12,1,'Затруднительны проходы к рабочим местам, высокая концентрация складирования материалов на перекрытиях.','ТБ',NULL,NULL,NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (35,12,1,'Нет лееров на этажах.','ТБ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (36,12,1,'Работают под действующим краном без касок.','ТБ,ОТ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (37,13,1,'Работники ДВ-АРС пъянство в ночь с 20-21.','ТБ,ОТ','Докладная Охрана','22.06.2020','Невельского','ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (38,13,1,'Журналы произв.работ. И материалов неполные данные.','Качество',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (39,13,1,'Доступность ключей от ворот и калиток.','ТБ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (40,14,1,'Провалы грунта вдоль оси 1.1','Качество',NULL,'23.06.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (41,15,1,'В проекте АР неправильное оформление, избыточное наполнение структуры полов, несоответствие другим альбомам КЖ. по П-1-15.','Качество',NULL,'30.06.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (42,16,1,'Кладка проемов выполняется с предельными отклонениями.','Качество',NULL,'02.07.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (43,16,1,'Рабочие ДВ-АРС не задействованные в строительстве проживают на территории объекта.','ТБ,ОТ',NULL,NULL,NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (44,16,1,'Недостаточное кол-во рабочих на кладке (всего 12чел.)','Сроки',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (45,16,1,'На отм.69.6 проем в венткамеру выполнен без учета толщины кровельного ковра.','Качество',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (46,16,1,'ДВ-АРС систематически нарушается технология по монтажу каркасов и опалубки, нет защитного слоя.','Качество',NULL,NULL,NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (47,17,1,'На исполнительных схемах монолитных конструкций нет технологических отверстий.','Качество',NULL,'02.07.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (48,17,1,'ДВ-АРС систематически нарушается технология по монтажу каркасов и опалубки, нет защитного слоя. Задержки по срокам.','Качество',NULL,NULL,NULL,'ДВ.АРС',112,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (49,17,1,'Нет актуальной информации по ГАСН',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (50,18,1,'Усиление кол. Сварочные швы нет качества.','Качество',NULL,'09.07.2020','Невельского',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (51,18,1,'Перемычки над проемами прилегающими к усиленным кол. Почему сразу не смонтировали опорные столики.','Качество','Фото 3654, 1113.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
INSERT INTO `` (`id`,`qcheckid`,`ordr`,`chkreport`,`category`,`proof`,`chkdate`,`objname`,`resporgname`,`resporgid`,`respstaffid`,`taskid`,`fixlimdate`,`fixfctdate`,`aprvstaffid`,`active`,`notes`,`created_at`,`created_by`,`updated_at`,`updated_by`) VALUES (52,18,1,'Запоздалые решения по инж.отверстиям.','Качество','Фото 1951.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'2020-07-15 22:21:05',1,'2020-07-15 22:21:05',1);
